behaviors:
  Agente:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
      buffer_size: 100
      learning_rate: 3.0e-4
      beta: 5.0e-4
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 4
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        strength: 0.02
        gamma: 0.99
        encoding_size: 256
        learning_rate: 3.0e-4
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 5000
    threaded: true

environment_parameters:
  free_spots:
    curriculum:
      - name: MyFirstLesson
        completion_criteria:
          measure: progress
          behavior: Agente
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.2
        value: 40.0
      - name: MySecondLesson 
        completion_criteria:
          measure: progress
          behavior: Agente
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.3
        value: 20.0
      - name: MyThirdLesson
        completion_criteria:
          measure: progress
          behavior: Agente
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.4
        value: 15.0
      - name: MyFourthLesson
        completion_criteria:
          measure: progress
          behavior: Agente
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 10.0
      - name: MyFifthLesson
        completion_criteria:
          measure: progress
          behavior: Agente
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8
        value: 5.0
      - name: MyLastLesson
        value: 2.0
    